apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        env:
        - name: HTTP_PROXY
          value: 192.168.2.28:3128
        - name: HTTP_PROXY
          value: 192.168.2.28:3128
        - name: NO_PROXY
          value: 10.217.1.0/24, kubenetes.default.svc, 10.217.0.0/16
